### ISSUE TITLE
Error Code 429 pushshift.io

### ISSUE THREAD

**Issue by shokkakhan** [kaito1410/AutoDD_Rev2#30]
On first time running, recieve the following:

C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psaw\PushshiftAPI.py:192: UserWarning: Got non 200 code 429
  warnings.warn("Got non 200 code %s" % response.status_code)
C:\Users\Shokkatweej\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psaw\PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")

And then stalls at 'Getting quick stats...'

**Comment by jeffrey-m-johnson** [comment]
I get this too. It appears to me to be the rate limiting imposed by the pushshift.io API.
I ran again with debug messages enabled and it seems to be running, albeit slowly with the rate limiting.

Some sort of progress indicator, such as a running counter of the number of reddit submissions analyzed, might be nice so that we know that it is still working.

**Comment by kaito1410** [comment]
A progress indicator sounds like a possible feature to add. Will put that on the todo list. Thanks guys!
