### ISSUE TITLE
Running with -sub wallstreetbets slow

### ISSUE THREAD

**Issue by marcellelek** [kaito1410/AutoDD_Rev2#31]
Hi there,

First of all thank you for your excellent work.

Running main.py with wallstreetbets sub option is incredibly slow. My thought is that because of the huge dataset, but processing one entry a second is not ideal.

Thank you frou your app.

**Comment by gobbedy** [comment]
I ran into the same issue. I'm working on a way that should speed things up by a factor of ~10x. Will share when done.

**Comment by kaito1410** [comment]
Thanks, would be nice to have some python experts optimize the runtimes.

**Comment by gobbedy** [comment]
@kaito1410 I should be done tomorrow or Tuesday. How should I share the code with you?

Collecting the yahoo finance data is now blazing fast. I couldn't optimize the reddit retrieval part because pushshift rate limits, so no amount of parallelism will yield a huge speedup.

Still the bottleneck was yahoo finance so it's much faster now.

**Comment by kaito1410** [comment]
Hi @gobbedy, thanks for doing the yfinance data part. Would love to see the code. I just made a major overhaul on the praw implementation because of the psaw issues, so a merge request would probabbly have a lot of conflicts. If you are willing to share your code, we can exchange private messages/email or we can set up a call if you like.

**Comment by gobbedy** [comment]
hey @kaito1410 ya for sure. i also overhauled it because i wanted to use pandas dataframes instead of lists, and a few other things. i'll explain by email. i'll let you decide what you want to keep. what's your e-mail address?

**Comment by gobbedy** [comment]
or if you prefer you can e-mail me gperr050@uottawa.ca

**Comment by kaito1410** [comment]
Awesome speed up on the entire script by @gobbedy. Closing for now
